# local with flask run
@base_url=http://127.0.0.1:8000

# @base_url=https://lexatlas-api-cdh3cghdc6eyc8gy.eastus2-01.azurewebsites.net/

# @base_url=https://api.lexatlas.cloud/


@api_key=supersecuredevtoken
 
# Basic GET request testing access to the API
GET {{base_url}}
X-API-Key: badtoken
Content-Type: application/json
Accept: application/json

# Basic GET request
###
GET {{base_url}}
X-API-Key: {{api_key}}
Content-Type: application/json
Accept: application/json